### ISSUE TITLE
Missing SharpCompress

### ISSUE THREAD

**Issue by Shouclack** [jellyfin/jellyfin-plugin-bookshelf#114]
It started 2 weeks ago, I tried change the order of the "metadata readers" but it changed nothing.
I use Jellyfin (v.10.9.11-docker) with Bookshelf V11 from Jellyfin stable default repo.

Thank you!

[2024-09-18 18:12:56.145 -04:00] [ERR] [46] MediaBrowser.Providers.Books.BookMetadataService: Error in "Comic Provider"
System.IO.FileNotFoundException: Could not load file or assembly 'SharpCompress, Version=0.36.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96'. The system cannot find the file specified.

File name: 'SharpCompress, Version=0.36.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96'
   at Jellyfin.Plugin.Bookshelf.Providers.ComicBookInfo.ComicBookInfoProvider.ReadMetadata(ItemInfo info, IDirectoryService directoryService, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicBookInfo.ComicBookInfoProvider.ReadMetadata(ItemInfo info, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicFileProvider.GetMetadata(ItemInfo info, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, Boolean isSavingMetadata, CancellationToken cancellationToken)

**Comment by crobibero** [comment]
Should already be fixed by https://github.com/jellyfin/jellyfin-plugin-bookshelf/pull/112. Just needs a new release

**Comment by Shouclack** [comment]
Thank you

Le jeu. 19 sept. 2024, 01 h 25, Cody Robibero ***@***.***> a
écrit :

**Comment by Shouclack** [comment]
I've git clone and compile the dll but same error but we can see Version=0.38 now, thanks:
[2024-09-19 20:04:00.778 -04:00] [ERR] [15] MediaBrowser.Providers.Books.BookMetadataService: Error in "Comic Provider"
System.IO.FileNotFoundException: Could not load file or assembly 'SharpCompress, Version=0.38.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96'. The system cannot find the file specified.

File name: 'SharpCompress, Version=0.38.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96'
   at Jellyfin.Plugin.Bookshelf.Providers.ComicBookInfo.ComicBookInfoProvider.ReadMetadata(ItemInfo info, IDirectoryService directoryService, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicBookInfo.ComicBookInfoProvider.ReadMetadata(ItemInfo info, IDirectoryService directoryService, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicFileProvider.GetMetadata(ItemInfo info, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshWithProviders(MetadataResult`1 metadata, TIdType id, MetadataRefreshOptions options, ICollection`1 providers, ItemImageProvider imageService, Boolean isSavingMetadata, CancellationToken cancellationToken)

**Comment by kkwpsi** [comment]
I think the installation instructions should be updated. The errors in question disappeared when I also copied SharpCompress.dll and ZstdSharp.dll to the target folder.
