### ISSUE TITLE
Comic Vine search of existing comic gets "Empty JSON" error.

### ISSUE THREAD

**Issue by michael-zock** [jellyfin/jellyfin-plugin-bookshelf#118]
If I try the "Identify" feature using the Comic Vine ID, I get errors like the following log section.

These are the two comic issues where I ran into it today:
https://comicvine.gamespot.com/aliens-fire-and-stone-1-chapter-one/4000-466290/
https://comicvine.gamespot.com/aliens-fire-and-stone-2-chapter-two/4000-468876/

Weirdly, it only happens with the first two issues of that miniseries, the final two work just fine if I search using the numeric IDs:
https://comicvine.gamespot.com/aliens-fire-and-stone-3-chapter-three/4000-471268/
https://comicvine.gamespot.com/aliens-fire-and-stone-4-chapter-four/4000-474584/

```
[2024-11-07 18:25:43.981 +01:00] [ERR] [61] MediaBrowser.Providers.Manager.ProviderManager: Provider "Comic Vine" failed to retrieve search results
System.Text.Json.JsonException: The JSON value could not be converted to System.Boolean. Path: $.results.has_staff_review | LineNumber: 0 | BytePositionInLine: 3135.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a boolean.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedBoolean(JsonTokenType tokenType)
   at System.Text.Json.Serialization.Converters.BooleanConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicVine.BaseComicVineProvider.FetchItemDetails[T](String apiId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicVine.BaseComicVineProvider.GetOrAddItemDetailsFromCache[T](String providerId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicVine.ComicVineMetadataProvider.GetSearchResults(BookInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2024-11-07 18:25:49.856 +01:00] [INF] [137] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-07 18:27:24.879 +01:00] [ERR] [137] MediaBrowser.Providers.Manager.ProviderManager: Provider "Comic Vine" failed to retrieve search results
System.Text.Json.JsonException: The JSON value could not be converted to System.Boolean. Path: $.results[1].has_staff_review | LineNumber: 0 | BytePositionInLine: 3096.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a boolean.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedBoolean(JsonTokenType tokenType)
   at System.Text.Json.Serialization.Converters.BooleanConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicVine.ComicVineMetadataProvider.GetSearchResultsInternal(BookInfo item, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicVine.ComicVineMetadataProvider.GetSearchResults(BookInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
```

**Comment by aradng** [comment]
similar thing happens for these aswell:
- invincible-87/4000-310923
- invincible-88/4000-313909
...
- invincible-110/4000-450044
- invincible-111/4000-452468

- before-watchmen-dr-manhattan-1-whats-in-the-box-th/4000-352465
- before-watchmen-dr-manhattan-3-ego-sum-the-curse-o/4000-372350
- before-watchmen-ozymandias-1-i-met-a-traveler-the-/4000-344230
- before-watchmen-ozymandias-3-the-heart-that-fed-th/4000-358825

almost 60% of metadata retrieval with comicvine_id is not working due to these errors
```
Apr 03 11:25:13 arad-nuc jellyfin[132513]: [11:25:13] [ERR] Provider Comic Vine failed to retrieve search results
Apr 03 11:25:13 arad-nuc jellyfin[132513]: System.Text.Json.JsonException: The JSON value could not be converted to System.Boolean. Path: $.results.has_staff_review | LineNumber: 0 | BytePositionInLine: 4926.
Apr 03 11:25:13 arad-nuc jellyfin[132513]:  ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a boolean.
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedBoolean(JsonTokenType tokenType)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    --- End of inner exception stack trace ---
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, JsonSerializerOptions options, CancellationToken cancellationToken)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at Jellyfin.Plugin.Bookshelf.Providers.ComicVine.BaseComicVineProvider.FetchItemDetails[T](String apiId, CancellationToken cancellationToken)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at Jellyfin.Plugin.Bookshelf.Providers.ComicVine.BaseComicVineProvider.GetOrAddItemDetailsFromCache[T](String providerId, CancellationToken cancellationToken)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at Jellyfin.Plugin.Bookshelf.Providers.ComicVine.ComicVineMetadataProvider.GetSearchResults(BookInfo searchInfo, CancellationToken cancellationToken)
Apr 03 11:25:13 arad-nuc jellyfin[132513]:    at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
Apr 03 11:25:14 arad-nuc jellyfin[132513]: [11:25:14] [ERR] Error response from Google Books API:  (status code: BadRequest)
```
also api calls are being made even when only comicvine_id fields is supplied which (to google) which is a waste IMO.

**Comment by IAmTurbanMan** [comment]
I am having similar things happen to these:

- ms-marvel-1-part-one-of-five-meta-morphosis/4000-444534
- ms-marvel-2-part-two-of-five-all-mankind/4000-447998
- ms-marvel-3-part-three-of-five-side-entrance/4000-450552
- ms-marvel-5-part-five-of-five-urban-legend/4000-457643
- ms-marvel-6-healing-factor-part-one/4000-459674
- ms-marvel-7-healing-factor-part-two-of-two/4000-462895
- ms-marvel-10-generation-why-part-three-of-four/4000-473653
- ms-marvel-11-generation-why-part-four-of-four/4000-478611
- ms-marvel-14-crushed-part-two-of-three/4000-486151
- ms-marvel-16-last-days-part-one/4000-492221

```
[2026-05-15 19:41:56.877 -04:00] [ERR] Provider "Comic Vine" failed to retrieve search results
System.Text.Json.JsonException: The JSON value could not be converted to System.Boolean. Path: $.results.has_staff_review | LineNumber: 0 | BytePositionInLine: 3206.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a boolean.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedBoolean(JsonTokenType tokenType)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicVine.BaseComicVineProvider.FetchItemDetails[T](String apiId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicVine.BaseComicVineProvider.GetOrAddItemDetailsFromCache[T](String providerId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bookshelf.Providers.ComicVine.ComicVineMetadataProvider.GetSearchResults(BookInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
```
